name: aplication

on:
  push:
    branches: # wykona się jeżeli wypchniemy commit na branch "hello world"
      - aplication
#    paths:   # wykona się jeżeli zmienimy jakiś plik w folderze "scripts"
#      - 'scripts/**'
jobs:
  build:
#    runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install build tools
        run: | 
          python -m pip install --upgrade pip
          pip install build

      - name: build package
        run: |
          python -m build --wheel --outdir dist

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel-package
          path: dist/*.whl