name: first on push main


on:
  push:
    branches:
      - main

jobs:
  deploy_on_rocky:
    runs-on: self-hosted
    steps:
      - name: print
        run: |
          echo "deploy rocky mutherfucker"