name: second workflow after first

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["first on push main"]
    types:
      - completed
jobs:
  deploy_on_debian:
    runs-on: self-hosted
#    runs-on: [self-hosted, debian]
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: print
        run: |
          echo "deploy debian manually mutherfucker"
