name: deploy to dev

on:
  workflow_call:
    inputs:
      deploy_env:
        required: true
        type: string

jobs:
  deploy_job:
    runs-on: self-hosted
    environment: ${{ inputs.deploy_env }}
    steps:
      - name: Run nginx deploy script
        run: ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/githubactions githubactions@10.250.2.24 "bash /srv/learning/postgres/deploy-postgres.sh"

