on:
  workflow_call:
    inputs:
      deploy_env:
        required: true
        type: string



jobs:
  check_permissions:
    runs-on: self-hosted
    steps:
      - name: Set up SSH key
        run: |
          echo "$HOME"
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/githubactions
          chmod 600 $HOME/.ssh/githubactions
      - name: get project folders permissions
        run: ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/githubactions githubactions@10.250.2.24 "ls -la /srv/learning/"
      - name: get files permissions nginx
        run: ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/githubactions githubactions@10.250.2.24 "ls -la /srv/learning/nginx/"
      - name: get files permissions postgres
        run: ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/githubactions githubactions@10.250.2.24 "ls -la /srv/learning/postgres"