name: deploy_debian

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["deploy rocky"]
    types:
      - completed
jobs:
  deploy_on_debian:
    runs-on: self-hosted
    steps:
      - name: print
        run: |
          echo "deploy debian manually mutherfucker"
