name: Hello-World

on:
  push:
    branches: # wykona się jeżeli wypchniemy commit na branch "hello world"
      - hello-world
#    paths:   # wykona się jeżeli zmienimy jakiś plik w folderze "scripts"
#      - 'scripts/**'

jobs:
  print-hello:
    name: Hello-world-name
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.12"]  # tutaj dodajesz wersje Pythona

    steps:
      - name: Checkout repository # klonowanie kodu z repozytorium do środowiska roboczego github actions
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: print hello world
        run: echo "Hello World"

      - name: create bash script
        run: echo "cat /etc/passwd" > ./list_users.sh

      - name: run bash script list_users.sh
        run: bash ./list_users.sh

      - name: list variables
        run: printenv

      - name: List repo root files
        run: ls -la

      - name: run script from
        run: python scripts/main.py

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run tests
        run: pytest





