name: Hello-World

on:
  push:
    branches:
      - hello-world

jobs:
  print-hello:
    name: Hello-world-name
    runs-on: ubuntu-latest

    steps:
      - name: print hello world
        run: echo "Hello World"




