name: lint test and deploy
on:
  push:
#    branches:
#      - learning
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: get code for lint
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
  test:
    runs-on: self-hosted
    needs: lint
    steps:
      - name: get code for test
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: test
        run: npm run test
  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: get code for build
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: deploy
        run: echo "deploying"

