name: lint test and deploy
on:
  push:
#    branches:
#      - learning
jobs:
  get_code:
    runs-on: self-hosted
    steps:
      - name: get code
        uses: actions/checkout@v4
  lint_and_test:
    runs-on: self-hosted
    needs: get_code
    steps:
      - name: install lint
        run: npm init @eslint/config@latest
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: deploy
        run: npm run build