name: lint test and deploy
on:
  push:
#    branches:
#      - learning
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: get code for lint
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
  build:
    runs-on: self-hosted
    needs: lint
    steps:
      - name: get code for test
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
#            package.json
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: get build artifacts
        uses: action/download-artifact@v4
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: deploy
        run: echo "deploy"



