name: manual

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Environment name'
        required: true
        default: 'staging'
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Print chosen environment
        run: echo "Deploying to environment ${{ github.event.inputs.env_name }}"
