name: third job manually

on:
  workflow_call:

jobs:
  deploy_job:
    runs-on: self-hosted
    steps:
      - name: read file
        run: cat dragon.txt
      - name: deploy
        run: echo Deploying ...