name: Matrix Demo
on:
  push:
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [14, 16, 18]
        operating-system: [ubuntu-latest, windows-latest]
        include:  # additional standalone configuration
          - node-version: 18
            operating-system: ubuntu-latest
            npm: 6
        exclude:
          - node-version: 14
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system}}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependenies
        run: npm ci
      - name: Build project
        run: npm run build