name: multiple jobs

on:
  push:

jobs:

  get_permissions_job:
    runs-on: self-hosted
    steps:
      - name: Set up SSH key
        run: |
          echo "$HOME"
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/githubactions
          chmod 600 $HOME/.ssh/githubactions
      - name: get project folders permissions
        run: ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/githubactions githubactions@10.250.2.24 "ls -la /srv/learning/
      - name: get files permissions nginx
        run: ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/githubactions githubactions@10.250.2.24 "ls -la /srv/learning/nginx/
      - name: get files permissions postgres
        run: ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/githubactions githubactions@10.250.2.24 "ls -la /srv/learning/postgres

  test_job:
    uses: ./.github/workflows/manualy_run_thid_job.yaml
    needs: build_job
    with:
      deploy_env: develop


  deploy_job:
    uses: ./.github/workflows/manualy_run_thid_job.yaml
    needs: [test_job,build_job]
    with:
      deploy_env: production



