name: multiple jobs

on:
  push:

jobs:

  check_permisionssion:
    runs-on: self-hosted
    outputs:
      CONTINUE_JOBS: ${{ steps.manual-trigger.outputs.CONTINUE_JOBS }}
    steps:
      - name: manual-trigger
        id: manual-trigger
        uses: benhamiltonpro/manual-trigger@v1.0.2
        with:
          RUN_NAME: "manual-step"
  step-awaiting-manual-trigger:
    runs-on: self-hosted
    needs: check_permisionssion
    if: ${{ needs.manual-step-name.outputs.CONTINUE_JOBS == 'true' }}
    steps:
      - name: run check permisions
        uses: ./.github/workflows/check_permissions.yaml




#      - name: first_workflow_debian_postgres
#        uses: ./.github/workflows/change_permissions.yaml
#        with:
#          RUN_NAME: "manual-step"


#    name: Verify Deployment Permissions
#    if: ${{ inputs.trigger_downstream }}
#    runs-on: self-hosted
#    uses: ./.github/workflows/check_permissions.yaml

#  change_permisionssion:
#    if: ${{ inputs.trigger_downstream }}
#    runs-on: self-hosted
#    steps:
#      - name: first_workflow_debian_postgres
#        uses: ./.github/workflows/change_permissions.yaml
#
#  deploy_postgres_debian:
#    name: deploy_postgres_debian
#    if: ${{ inputs.trigger_downstream }}
#    runs-on: self-hosted
#    needs: [check_permissions]
#    uses: ./.github/workflows/first_workflow_debian_postgres.yaml
#
##        with:
##          repository: owner/downstream_repository
##          client-payload: '{"branch": "main"}'
#  deploy_nginx_debian:
#    if: ${{ inputs.trigger_downstream }}
#    runs-on: self-hosted
#    steps:
#      - name: first_workflow_debian_postgres
#        uses: ./.github/workflows/second_workflow_neginx_debian.yaml
#
#
#  deploy_nginx_rocky:
#    if: ${{ inputs.trigger_downstream }}
#    runs-on: self-hosted
#    steps:
#      - name: deploy_nginx_rocky
#        uses: ./.github/workflows/third_workflow_neginx_rocky.yaml
#
#
#  deploy_postgres_rocky:
#    if: ${{ inputs.trigger_downstream }}
#    runs-on: self-hosted
#    steps:
#      - name: deploy_nginx_rocky
#        uses: ./.github/workflows/fourth_workflow_postgres_rocky.yaml

# first_workflow_debian_postgres.yaml
# second_workflow_neginx_debian.yaml
# third_workflow_neginx_rocky.yaml
# fourth_workflow_postgres_rocky.yaml