name: multiple jobs

on:
  push:
  workflow_dispatch:
    inputs:
      trigger_downstream:
        type: boolean
        description: 'Trigger downstream pipeline?'
        required: false
        default: false

jobs:
  check_permisionssion:
    if: ${{ github.event.inputs.trigger_downstream == 'true' }}
    runs-on: self-hosted
    steps:
      - name: first_workflow_debian_postgres
        uses: ./.github/workflows/check_permissions.yaml

  change_permisionssion:
    if: ${{ github.event.inputs.trigger_downstream == 'true' }}
    runs-on: self-hosted
    steps:
      - name: first_workflow_debian_postgres
        uses: ./.github/workflows/change_permissions.yaml

  deploy_postgres_debian:
    if: ${{ github.event.inputs.trigger_downstream == 'true' }}
    runs-on: self-hosted
    steps:
      - name: first_workflow_debian_postgres
        uses: ./.github/workflows/first_workflow_debian_postgres.yaml

#        with:
#          repository: owner/downstream_repository
#          client-payload: '{"branch": "main"}'
  deploy_nginx_debian:
    if: ${{ github.event.inputs.trigger_downstream == 'true' }}
    runs-on: self-hosted
    steps:
      - name: first_workflow_debian_postgres
        uses: ./.github/workflows/second_workflow_neginx_debian.yaml


  deploy_nginx_rocky:
    if: ${{ github.event.inputs.trigger_downstream == 'true' }}
    runs-on: self-hosted
    steps:
      - name: deploy_nginx_rocky
        uses: ./.github/workflows/third_workflow_neginx_rocky.yaml


  deploy_postgres_rocky:
    if: ${{ github.event.inputs.trigger_downstream == 'true' }}
    runs-on: self-hosted
    steps:
      - name: deploy_nginx_rocky
        uses: ./.github/workflows/fourth_workflow_postgres_rocky.yaml

# first_workflow_debian_postgres.yaml
# second_workflow_neginx_debian.yaml
# third_workflow_neginx_rocky.yaml
# fourth_workflow_postgres_rocky.yaml