name: multiple jobs

on: push

jobs: 
  build_job:
    runs-on: self-hosted
    steps:
    - name: install cowsay program
      run: sudo apt-get install cowsay -y
    - name: execute cowsay cmd
      run: cowsay -f dragon "Run for cover, I am a DRAGON .... RAWR" >> dragon.txt

  test_job:
    needs: build_job
    runs-on: self-hosted
    steps:
    - name: sleep for 10 seconds
      run: sleep 10
    - name: test file exists
      run: grep -i "dragon" dragon.txt

  deploy_job:
    runs-on: self-hosted
    needs: test_job
    steps:
     - name: third job
       run: echo "third job