name: multiple jobs

on: push

jobs: 
  build_job:
    runs-on: self-hosted
    steps:
    - name: install cowsay program
      run: sudo apt-get install cowsay -y
    - name: execute cowsay cmd
      run: cowsay -f dragon "Run for cover, I am a DRAGON .... RAWR" ?? dragon.txt
    - name: sleep for 30 seconds
      run: sleep 30
  test_job:
    runs-on: self-hosted
    steps:
    - name: sleep for 10 seconds
      run: sleep 10
    - name: test file exists
      run: grep -i "dragon" dragon.txt

  deply_job:
    runs-on: self-hosted
    steps:
      - name: read file
        run: cat dragon.txt
      - name: deploy
        run: echo Deploying ...