
###### nie działa, problem z modułami '@actions/core' oraz '@actions/exec');




name: node-action

on:
  workflow_call:
    inputs:
      target-host:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  check-message:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run custom commit message check
        uses: ./my-node-action
        with:
          min-length: 15

