name: node-action

on:
  workflow_call:
    inputs:
      target-host:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  node:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: npm install
        run: | 
          apt update
          apt install npm

      - name: Uruchom moją akcję
        uses: ./my-node-action  # albo ./my-docker-action
        with:
          name: Dzbanek

