name: passing_data_between_jobs

on:
  workflow_dispatch:

jobs:
  data-passing:
    runs-on: ubuntu-latest
    steps:
      - name: Create data
        id: create_id
        run: |
          echo "name=Lukasz" >> $GITHUB_OUTPUT
    outputs:
      data: ${{ steps.create_id.outputs.name }}
  data-reciever:
    runs-on: ubuntu-latest
    steps:
      - name: Recieve Data
        run: |
          echo ${{ needs.data-passing.outputs.data }}
