name: passing_data_between_steps

on:
  workflow_dispatch:

jobs:
  data-passing:
    runs-on: ubuntu-latest
    steps:
      - name: Create data
        id: create
        run: |
          echo "name=Lukasz" >> $GITHUB_OUTPUT
      - name: Recieve Data
        run: |
          echo ${{ steps.create.outputs.name }}
# aa