name: aaa


on:
  push:
    branches: # wykona się jeżeli wypchniemy commit na branch "aaa"
      - aaa
      -
jobs:
  deploy:
    runs-on: self-hosted
    #    container:
    #      image: node:18
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4