name: Test mojej akcji

on:
  workflow_dispatch:
    inputs:
      pipeline:
        description: 'Który pipeline uruchomić?'
        required: true
        type: choice
        options:
          - docker-action
          - node-action



jobs:
  docker-action:
    if: ${{ github.event.inputs.pipeline == 'docker-action' }}
    uses: ./.github/workflows/run_apps.yaml
    with:
      target-host: '10.250.2.24'
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}


  node-action:
    if: ${{ github.event.inputs.pipeline == 'node-action' }}
    uses: ./.github/workflows/run_apps.yaml
    with:
      target-host: '10.250.2.25'
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

