name: run_apps_on_debian

on:
  workflow_call:
    inputs:
      target-host:
        required: true
        type: string


jobs:
  deploy:
    runs-on: self-hosted
#    container:
#      image: node:18

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p $HOME/.ssh
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/githubactions

      - name: Run nginx deploy script
        run: ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/githubactions githubactions@${{ inputs.target-host }} "bash /srv/learning/nginx/deploy-nginx.sh"

      - name: Run postgres deploy script
        run: ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/githubactions githubactions@${{ inputs.target-host }} "bash /srv/learning/postgres/deploy-postgres.sh "
  #    - name: run nginx container
  #      run: ssh -o StrictHostKeyChecking=no githubactions@{{ inputs.target-host }} "bash /srv/learning/nginx/deploy-nginx.sh"
      - name: Cleanup SSH key
        run: rm -f $HOME/.ssh/githubactions
