name: run_apps

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Environment name'
        required: true
        default: 'staging'

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: node:18

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh -vvv githubactions@10.250.2.24 exit
          ssh -o StrictHostKeyChecking=no githubactions@10.250.2.24
      - name: run nginx container
        run: ssh -o StrictHostKeyChecking=no githubactions@10.250.2.24 "bash /srv/learning/nginx/deploy-nginx.sh"

